### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by alz10** [p3hndrx/MLBB-EquipmentPlanner#1]
Nice work, I've read your [reddit thread here](https://www.reddit.com/r/MobileLegendsGame/comments/fafmmm/new_mobilelegends_fanbased_api/). 

Some chinese guy publish a new app [Mobile Legends: Pocket](https://play.google.com/store/apps/details?id=com.miya.mobile&hl=en) this seems to be heavily api based because he can incorporate players data and use your actual mobile legends accounts to login to his app. I wonder where he get this apis, he could probably be working in Moonton i guess.

btw, im the developer of this app [ML Pocket Guide](https://play.google.com/store/apps/details?id=com.notsouglygames.mobilelegendsperfectguide&hl=en)

**Comment by p3hndrx** [comment]
@alz10 
Thanks for the comments!
I think ML:Pocket is an official app... the user data is on-point. ^_^

I also enjoy ML Pocket Guide, we use it all the time.
The original goal of the API was to develop an app that will let you save/share builds to forum/facebook and to automatically calculate how your attributes change when you choose specific items. I realized we didn't have the full data set of items/heroes/emblems, so I started to build the data from scratch.

Maybe this could be a feature for ML Pocket Guide?

**Comment by alz10** [comment]
> Maybe this could be a feature for ML Pocket Guide?

Yeah sure but I'm busy in work and currently working on MC Pocket Guide (Magic Chess and Chess TD Guide). I already published the app on playstore but it could have been easier for us devs if Moonton release an offical API and that's impossible to happen LOL
